<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Abelia × grandiflora',
                'code' => '90172580',
                'type' => '1',
                'attribute' => 'null',
                'max_discount' => '1',
                'markup' => '1',
                'size' => '28',
                'common_name' => 'Abelia × grandiflora',
                'family_name' => 'Abelia × grandiflora',
                'sku' => '2343',
                'barcode_symbology' => 'UPCE',
                'vendor_product_id' => 1,
                'brand_id' => 1,
                'category_id' => 2,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '100',
                'price' => '12',
                'qty' => 0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => '202203240655282.jpg',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 0,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'created_at' => '2022-03-22 11:13:50',
                'updated_at' => '2022-03-24 18:58:20',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Abelia',
                'code' => '79221939',
                'type' => '1',
                'attribute' => 'null',
                'max_discount' => '1',
                'markup' => '1',
                'size' => '11',
                'common_name' => 'Abelia',
                'family_name' => 'Abelia',
                'sku' => 'Abelia',
                'barcode_symbology' => 'UPCE',
                'vendor_product_id' => 2,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '300',
                'price' => '500',
                'qty' => 0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => '164792680123619b398f1f9934e9a96dc8fe8fd949bd1.jpg',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 1,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'created_at' => '2022-03-22 11:32:38',
                'updated_at' => '2022-03-26 18:18:51',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Dioscorea sansibarensis',
                'code' => '43825794',
                'type' => '1',
                'attribute' => 'null',
                'max_discount' => '1',
                'markup' => '1',
                'size' => '12',
                'common_name' => 'Dioscorea',
                'family_name' => 'Dioscorea',
                'sku' => 'Dioscorea',
                'barcode_symbology' => 'UPCE',
                'vendor_product_id' => 6,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '12',
                'price' => '550',
                'qty' => 0,
                'alert_quantity' => 11.0,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => '16479273806587783ba3ca51b4c4982b531d210652d20.jpg',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 1,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'created_at' => '2022-03-22 11:32:38',
                'updated_at' => '2022-03-22 12:41:55',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Campnosperma squamatum Ridl',
                'code' => '9898',
                'type' => '1',
                'attribute' => 'null',
                'max_discount' => '1',
                'markup' => '1',
                'size' => '23',
                'common_name' => 'Campnosperma squamatum Ridl',
                'family_name' => 'Campnosperma squamatum Ridl',
                'sku' => 'Campnosperma squamatum Ridl',
                'barcode_symbology' => 'UPCE',
                'vendor_product_id' => 7,
                'brand_id' => 1,
                'category_id' => 2,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '100',
                'price' => '1',
                'qty' => 0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => '202203240631552.jpg',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 1,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'created_at' => '2022-03-22 12:16:35',
                'updated_at' => '2022-03-24 18:31:55',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Real',
                'code' => 'dasdasds',
                'type' => '1',
                'attribute' => NULL,
                'max_discount' => NULL,
                'markup' => NULL,
                'size' => NULL,
                'common_name' => NULL,
                'family_name' => NULL,
                'sku' => NULL,
                'barcode_symbology' => NULL,
                'vendor_product_id' => 8,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '2001',
                'price' => '444',
                'qty' => 0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => NULL,
                'image' => '1647930222130Signature5nov1.jpg',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 2,
                'created_at' => '2022-03-22 12:47:48',
                'updated_at' => '2022-03-24 18:56:43',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Goeppertia elliptica \'Vittata\'',
                'code' => '1234',
                'type' => '1',
                'attribute' => '9',
                'max_discount' => '0',
                'markup' => 'Doloremque culpa ut',
                'size' => '7',
                'common_name' => 'Leah Strong',
                'family_name' => 'Goeppertia elliptica',
                'sku' => 'Dicta et quae est es',
                'barcode_symbology' => 'UPCE',
                'vendor_product_id' => 9,
                'brand_id' => 1,
                'category_id' => 2,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '75',
                'price' => '99',
                'qty' => 0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => '202203240633242.jpg',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 0,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'created_at' => '2022-03-22 16:16:10',
                'updated_at' => '2022-03-24 18:33:24',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Agave vilmoriniana',
                'code' => '12344321',
                'type' => '1',
                'attribute' => 'null',
                'max_discount' => '0',
                'markup' => 'Maxime reprehenderit',
                'size' => '5',
                'common_name' => 'Agave vilmoriniana',
                'family_name' => 'Agave vilmoriniana',
                'sku' => 'Agave vilmoriniana',
                'barcode_symbology' => 'UPCE',
                'vendor_product_id' => 10,
                'brand_id' => 1,
                'category_id' => 2,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '80',
                'price' => '66',
                'qty' => 0,
                'alert_quantity' => 77.0,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => '202203240634172.JPG',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 0,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'created_at' => '2022-03-22 16:16:10',
                'updated_at' => '2022-03-24 18:34:17',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Abelia grandiflora',
                'code' => '18436903',
                'type' => '1',
                'attribute' => 'null',
                'max_discount' => '1',
                'markup' => '1',
                'size' => '23',
                'common_name' => 'Abelia grandiflora',
                'family_name' => 'Abelia grandiflora',
                'sku' => 'Abelia grandiflora',
                'barcode_symbology' => 'UPCE',
                'vendor_product_id' => 11,
                'brand_id' => 1,
                'category_id' => 2,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '55',
                'price' => '22',
                'qty' => 0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => '202203240653592.jpg',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 0,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'created_at' => '2022-03-22 16:16:10',
                'updated_at' => '2022-03-24 18:53:59',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Sample New',
                'code' => '111112',
                'type' => '1',
                'attribute' => NULL,
                'max_discount' => NULL,
                'markup' => NULL,
                'size' => NULL,
                'common_name' => NULL,
                'family_name' => NULL,
                'sku' => NULL,
                'barcode_symbology' => NULL,
                'vendor_product_id' => 12,
                'brand_id' => 1,
                'category_id' => 2,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => '45',
                'price' => NULL,
                'qty' => 0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => NULL,
                'image' => '1647949812983logo-pnrao.png',
                'file' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'is_active' => 2,
                'created_at' => '2022-03-22 17:46:35',
                'updated_at' => '2022-03-24 18:58:07',
            ),
        ));
        
        
    }
}