<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => '$2y$10$DWAHTfjcvwCpOCXaJg11MOhsqns03uvlwiSUOQwkHL2YYrtrXPcL6',
                'remember_token' => 'VkVp5nz2jaekalrW5UpxQElLBi3saVDH2vqFLfEkOwYNPFOaPvOwdlKUORVG',
                'phone' => '12112',
                'company_name' => 'Pixel Studios',
                'role_id' => 1,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => NULL,
                'is_active' => 1,
                'is_deleted' => 0,
                'created_at' => '2018-06-02 08:54:15',
                'updated_at' => '2022-02-10 17:54:13',
            ),
            1 => 
            array (
                'id' => 107,
                'name' => 'Moses Lester',
                'email' => 'lester@mailinator.com',
                'password' => '$2y$10$MtZnElNDCISkwIaSAmHjM.kZ8hXf2/MY1fqdShJ2AIJNsxrNNc3Mi',
                'remember_token' => NULL,
                'phone' => '4161111111',
                'company_name' => 'Larson Wilkerson Plc',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '132',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 16:20:59',
                'updated_at' => '2022-02-28 16:20:59',
            ),
            2 => 
            array (
                'id' => 108,
                'name' => 'Zia Everett1',
                'email' => '67santhosh@gmail.com',
                'password' => '$2y$10$TB9SQdSacL.VsudELPn/qe44UK9PEEKK3103YeuLHxYhCWKwH9SZS',
                'remember_token' => 'vCeEqvhWKOgvYRNGFwY7RZ5xSIchlgyFzeeKQSk3kUee0lQybrP9nLYFsQY1',
                'phone' => '5081111110',
                'company_name' => 'Hatfield Guzman Co1',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '133',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 16:22:05',
                'updated_at' => '2022-03-01 18:09:50',
            ),
            3 => 
            array (
                'id' => 109,
                'name' => 'Trevor Talley1',
                'email' => 'qitijile@mailinator.com',
                'password' => '$2y$10$DQCcfmsjL/vvnC1DnLy9feFg6O0IUNs8DYfSt848xUFFpiYF/AuqG',
                'remember_token' => NULL,
                'phone' => '4681111111',
                'company_name' => 'Gross Bush Co',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '134',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 16:34:44',
                'updated_at' => '2022-02-28 16:35:32',
            ),
            4 => 
            array (
                'id' => 110,
                'name' => 'Nell Casey',
                'email' => 'nyrilimad@mailinator.com',
                'password' => '$2y$10$iaYYl8inNLs0XBmYOsKCF.128UzD8aXMyegIWiY84z6TrKz7vSlX6',
                'remember_token' => NULL,
                'phone' => '2871111111',
                'company_name' => 'Hopkins and Guzman Traders',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '135',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 16:35:55',
                'updated_at' => '2022-02-28 16:35:55',
            ),
            5 => 
            array (
                'id' => 111,
                'name' => 'Cathleen Whitney',
                'email' => 'zetubCathleenad@mailinator.com',
                'password' => '$2y$10$abBHqq0l3YQbCEVwFQZFwOZhYbpaKqPbt2ZKomWqJRcqGJN357YB.',
                'remember_token' => NULL,
                'phone' => '7711111111',
                'company_name' => 'Vasquez Hogan Associates',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '136',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 16:41:32',
                'updated_at' => '2022-02-28 16:41:32',
            ),
            6 => 
            array (
                'id' => 112,
                'name' => 'Giselle Solomon',
                'email' => 'hyges@mailinator.com',
                'password' => '$2y$10$yWfZWLV2VrZVazmgLgIrTOGbWB17JrD8cMJNaPoCf9r0UuuGPBa4K',
                'remember_token' => NULL,
                'phone' => '6841111111',
                'company_name' => 'Macdonald and Holcomb Inc',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '137',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 16:42:18',
                'updated_at' => '2022-02-28 19:18:27',
            ),
            7 => 
            array (
                'id' => 113,
                'name' => 'Chastity Warner',
                'email' => 'ticyvi@mailinator.com',
                'password' => '$2y$10$mrPamh5uGpzWf7MMpTKVV.GPnM8MopCnsintu/sbAivHlJmRjDIbG',
                'remember_token' => NULL,
                'phone' => '3325454545',
                'company_name' => 'Spencer and Sullivan Associates',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '138',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 19:26:05',
                'updated_at' => '2022-02-28 19:26:05',
            ),
            8 => 
            array (
                'id' => 114,
                'name' => 'Callum Moreno',
                'email' => 'pixel@pixel.com',
                'password' => '$2y$10$hWXnwTF1EErc79ictSRZ9ejeCoScFEvu/jkQfSgAvFftrDBTYvA.6',
                'remember_token' => NULL,
                'phone' => '7358244164',
                'company_name' => 'donitus',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '139',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-02-28 19:27:10',
                'updated_at' => '2022-03-01 10:43:40',
            ),
            9 => 
            array (
                'id' => 115,
                'name' => 'Solomon Guerra',
                'email' => 'vuzot@mailinator.com',
                'password' => '$2y$10$QjUPJU4OA.iEZ3LAhvt5K.atPqf1bpI8fh4Chs9V6BHIfA55SWqxq',
                'remember_token' => NULL,
                'phone' => '5701111111',
                'company_name' => 'Clarke and Mathis Inc',
                'role_id' => 1,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '140',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-01 11:06:11',
                'updated_at' => '2022-03-01 11:06:11',
            ),
            10 => 
            array (
                'id' => 116,
                'name' => 'Yuli Velasquez',
                'email' => 'sijodyg@mailinator.com',
                'password' => '$2y$10$AAGC0IiHAseWW5iLDz2RtOY6tuE.x2l/Zsd8RCnn7AbLwDhaJeDYS',
                'remember_token' => NULL,
                'phone' => '7060000000',
                'company_name' => 'Dixon Burke Plc',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '141',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-01 11:13:27',
                'updated_at' => '2022-03-01 11:13:27',
            ),
            11 => 
            array (
                'id' => 117,
                'name' => 'Thane Reese',
                'email' => 'keloqosigy@mailinator.com',
                'password' => '$2y$10$9ygds7B6BjhcmV7l6XJCoOXi0/W9iABnJ4keRZRs0fF8UYgWg.K4y',
                'remember_token' => NULL,
                'phone' => '5341111111',
                'company_name' => 'Kline Hooper Trading',
                'role_id' => 1,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '142',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-01 20:26:00',
                'updated_at' => '2022-03-01 20:26:00',
            ),
            12 => 
            array (
                'id' => 118,
                'name' => 'Donovan Curry',
                'email' => 'kodis@mailinator.com',
                'password' => '$2y$10$nNEwy9j9VnRzzbyLXi.CtOjwLUtgwx7m4/JbErCN79ebDhlF4MStK',
                'remember_token' => NULL,
                'phone' => '8001111111',
                'company_name' => 'Cortez and Glenn Traders',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '143',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:27:07',
                'updated_at' => '2022-03-03 10:27:07',
            ),
            13 => 
            array (
                'id' => 119,
                'name' => 'Rajah Salas',
                'email' => 'jyvu@mailinator.com',
                'password' => '$2y$10$6.ayN/AUM0MY5Pfy74eD8OySnun2K5MKoFkfgZrqvGSfPng8zTm.S',
                'remember_token' => NULL,
                'phone' => '3831111111',
                'company_name' => 'Avila French LLC',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '144',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:28:37',
                'updated_at' => '2022-03-03 10:28:37',
            ),
            14 => 
            array (
                'id' => 120,
                'name' => 'Quinlan Combs',
                'email' => 'dubys@mailinator.com',
                'password' => '$2y$10$3SDy9otr1bLhiNBLq6u3COUkRuXQWL4zmrf8YnYpeAvHfq1IouL3a',
                'remember_token' => NULL,
                'phone' => '9591111111',
                'company_name' => 'Munoz Garza Plc',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '145',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:30:21',
                'updated_at' => '2022-03-03 10:30:21',
            ),
            15 => 
            array (
                'id' => 121,
                'name' => 'Ruby Booker',
                'email' => 'xexomyqet@mailinator.com',
                'password' => '$2y$10$ryiCmCyb1pgd9zBSnYwTFOSwOxwffmlBzTw3HBx8XbvlbsXsUc2cm',
                'remember_token' => NULL,
                'phone' => '4828888888',
                'company_name' => 'Ramsey Delacruz Trading',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '146',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:31:15',
                'updated_at' => '2022-03-03 10:31:15',
            ),
            16 => 
            array (
                'id' => 122,
                'name' => 'Noelle Case',
                'email' => 'cozuqeq@mailinator.com',
                'password' => '$2y$10$3YeUk78yPHFiFKt7rtCU6e34g8p4My9icdbl4Qo1/uu6m8mHziOSi',
                'remember_token' => NULL,
                'phone' => '6101111111',
                'company_name' => 'Butler and Hernandez Inc',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '147',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:34:40',
                'updated_at' => '2022-03-03 10:34:40',
            ),
            17 => 
            array (
                'id' => 123,
                'name' => 'Silas Santana',
                'email' => 'hygaw@mailinator.com',
                'password' => '$2y$10$0qnTmS8cnxzfgAFUTlk/rOx1iEW/gGWnydV5W82QWaIJNwAs/h.U2',
                'remember_token' => NULL,
                'phone' => '5801111111',
                'company_name' => 'Baker Winters Trading',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '148',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:35:17',
                'updated_at' => '2022-03-03 10:35:17',
            ),
            18 => 
            array (
                'id' => 124,
                'name' => 'Brendan Witt',
                'email' => 'sulad@mailinator.com',
                'password' => '$2y$10$wyD4RpUNaM1mQ/IQPHa6eungCh9cvru1qqiv6MZQVfNoVQgjLmUFa',
                'remember_token' => NULL,
                'phone' => '1319999990',
                'company_name' => 'Obrien Ellis Trading',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '149',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:36:47',
                'updated_at' => '2022-03-03 10:36:47',
            ),
            19 => 
            array (
                'id' => 125,
                'name' => 'Suki Obrien',
                'email' => 'dyqydafo@mailinator.com',
                'password' => '$2y$10$LaO1qIFH3BwfkLLowzG9UuDoDYvPf1tJOWt.aRORwyl82veqe0ori',
                'remember_token' => NULL,
                'phone' => '5281111111',
                'company_name' => 'Briggs Jensen Inc',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '150',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:37:21',
                'updated_at' => '2022-03-03 10:37:21',
            ),
            20 => 
            array (
                'id' => 126,
                'name' => 'Whitney Good',
                'email' => 'rulyxile@mailinator.com',
                'password' => '$2y$10$wTLZS.LuJTSvmeGc9ikjje.cFQehiwZSvjSpvzLleA0ZaxjPK7ZDm',
                'remember_token' => NULL,
                'phone' => '7481111111',
                'company_name' => 'Camacho and Vaughn Associates',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '151',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 10:37:47',
                'updated_at' => '2022-03-03 10:37:47',
            ),
            21 => 
            array (
                'id' => 127,
                'name' => 'Angela Rowe',
                'email' => 'hexup@mailinator.com',
                'password' => '$2y$10$XwLnDvHNVy/jVHI5HY5P6OT3jc8/C3I8wwVSTOezPBUr1wMDelZBS',
                'remember_token' => NULL,
                'phone' => '7561111111',
                'company_name' => 'Collier Ayala Traders',
                'role_id' => 6,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => '152',
                'is_active' => 1,
                'is_deleted' => NULL,
                'created_at' => '2022-03-03 15:47:56',
                'updated_at' => '2022-03-03 15:47:56',
            ),
            22 => 
            array (
                'id' => 128,
                'name' => 'Clinton Burks',
                'email' => 'lati@mailinator.com',
                'password' => 'Pa$$w0rd!',
                'remember_token' => NULL,
                'phone' => '7741111111',
                'company_name' => 'Carter and Santos Associates',
                'role_id' => 5,
                'biller_id' => NULL,
                'warehouse_id' => NULL,
                'vendor_id' => NULL,
                'is_active' => 1,
                'is_deleted' => 0,
                'created_at' => '2022-03-04 15:59:03',
                'updated_at' => '2022-03-04 15:59:03',
            ),
        ));
        
        
    }
}